// Export all landing page components
export { default as Navbar } from './Navbar'
export { default as MobileMenu } from './MobileMenu'
export { default as Hero } from './Hero'
export { default as HeroFitnessIllustration } from './HeroFitnessIllustration'
export { default as HeroAnimatedBackground } from './HeroAnimatedBackground'
export { default as SocialProof } from './SocialProof'
export { default as Features } from './Features'
export { default as HowItWorks } from './HowItWorks'
export { default as Testimonials } from './Testimonials'
export { default as Pricing } from './Pricing'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'
