// Export all auth components
export { default as RegisterStep1 } from './RegisterStep1'
export { default as RegisterStep2 } from './RegisterStep2'
export { default as RegisterStep3 } from './RegisterStep3'
export { default as RegisterStep4 } from './RegisterStep4'
export { default as RegisterStep5 } from './RegisterStep5'
export { default as StepIndicator } from './StepIndicator'
export { default as RegisterStepper } from './RegisterStepper'
export { default as MobileMenu } from './MobileMenu'
export { default as LoginIllustration } from './LoginIllustration'
export { default as LoginAnimatedBackground } from './LoginAnimatedBackground'
export { default as AuthPageHeader } from './AuthPageHeader'
export { default as RegisterIllustration } from './RegisterIllustration'
export { default as RegisterLayout } from './RegisterLayout'
